### PR TITLE
TranSMART Release Support / TRANSREL-9

### PR DESCRIPTION
**Pull request by sdenizot**
BUG: TRANSREL-9: Missing Associated Assays / Associated Analyses / Associated Folders. Issue in Browse (with postgres and oracle).
2 files
/biomart-domain-1.2.2-SNAPSHOT/grails-app/domain/org/transmart/biomart/BioAssayAnalysis.groovy
/biomart-domain-1.2.2-SNAPSHOT/grails-app/domain/org/transmart/biomart/BioAssayAnalysisData.groovy

### CODE REVIEW

**Comment by cataphract** [comment]
This change breaks GWAS for me. Also, commenting out lines of code with no explanation is almost universally a bad idea (What's the relevance of the code? Why was it commented out and not deleted? I have no idea).

Error:

<pre>
| Error 2016-04-22 12:46:18,563 [http-nio-8080-exec-3] ERROR errors.GrailsExceptionResolver  - QueryException occurred when processing request: [GET] /transmart/GWAS/getTrialAnalysis/392815495 - parameters:
unqKey: 1461321962702
_: 1461321962287
trialNumber: 392815495
could not resolve property: ext of: org.transmart.biomart.BioAssayAnalysis [select b.id AS bioAssayAnalysis, b.shortDescription, b.longDescription, b.name,c.sensitiveDesc, b.etlId  from org.transmart.biomart.BioAssayAnalysis b LEFT JOIN b.ext c  WHERE b.id in (392815493,392815494) ORDER BY b.longDescription]. Stacktrace follows:
Message: could not resolve property: ext of: org.transmart.biomart.BioAssayAnalysis [select b.id AS bioAssayAnalysis, b.shortDescription, b.longDescription, b.name,c.sensitiveDesc, b.etlId  from org.transmart.biomart.BioAssayAnalysis b LEFT JOIN b.ext c  WHERE b.id in (392815493,392815494) ORDER BY b.longDescription]
</pre>

**Comment by cataphract** [comment]
Apparently Terry got to the same conclusion, https://github.com/tranSMART-Foundation/transmart-extensions/commit/c40d1422e5258c1fc23af16c366071bcdd277408 but forgot to revert this in this repository...

**Comment by cataphract** [comment]
Reverted in `4c0aa70f8c80ed2edf6c1d64331f4ff3c8c1ad8c`.

**Comment by Terry-Weymouth** [comment]
Ah, sorry about that! I assume that the above revert "fixes" the problem. Yes? Thanks.

**Comment by cataphract** [comment]
It does for GWAS, I don't know exactly what problem this was supposed to browse (the ticket lists different issues), but for my purposes it doesn't matter. Anyway, I assume `master` will have the `v1.2.5-beta` branches merged into it after the release and the whole divergence problem goes away then, so it shouldn't matter that much if some aspect of browse is broken now on `master`.

**Pull request merged**
